site_name: WEB-Labs
nav:
  - Home: index.md
  - 1 lab:
      - Task 1: lr1/task1.md
      - Task 2: lr1/task2.md
      - Task 3: lr1/task3.md
      - Task 4: lr1/task4.md
      - Task 5: lr1/task5.md
  - 2 lab:
    - "Лабораторная работа": lr2/lab2.md
theme:
  name: readthedocs